site_name:           ArbFloats
site_url:            https://github.com/JuliaArbTypes/ArbFloats.jl
repo_url:            https://github.com/JuliaArbTypes/ArbFloats.jl
site_description:    Faster floating point math with 100..4000 bits
site_author:         Jeffrey Sarnoff
copyright:           © 2016 by Jeffrey Sarnoff.  The MIT license applies.
theme:               readthedocs

markdown_extensions:
  - codehilite
  - tables
  - fenced_code
  - extra
  - footnotes
  - toc
  - abbr
  - nl2br
  - smart_strong
  - sane_lists
  - attr_list
  - def_list
  - smarty
  - mdx_math

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Tutorial:
  - Overview: tutorial/page1.md
  - Getting Started: tutorial/page2.md
  - Floating Point Math: tutorial/page3.md
  - Guidelines: tutorial/page4.md
- Reference:
  - Scope: reference/page1.md
  - Precision: reference/page2.md
  - Types: reference/page3.md
  - Basic Functions: reference/page3.md
  - Math Functions: reference/page3.md
  - Support Functions: reference/page4.md